export const emoji = {
  awan: "⛅",
  pintu: "🚪",
  lampu: "💡",
  kedip: "😉",
  kacamata: "😎",
  menangis: "😭",
  lelah: "😪",
  sedih: "😓",
  semprit: "🥳",
  salaman: "🤝🏻",
  jempol: "👍🏻",
  angkattangan: "🖐",
  hai: "👋",
  kepalan: "👊",
  semangat: "✊",
  tunjuk: "👈",
  programmer: "👨🏻‍💻",
  ilmuwan: "👨🏻‍🔬",
  menyerah: "🤷‍♂️",
  jembatan: "🌉",
  buku: "📕",
  waktu: "⏱️",
  tanggal: "📅",
  edit: "📝",
  bataswaktu: "⌛",
  rumah: "🏠",
  dunia: "🌎",
  profil: "🙎🏻‍♂️",
  lonceng: "🔔",
  hore: "🎉",
  roket: "🚀",
  mata: "👀",
  ngacung: "🙋‍♂️",
  kembali: "⬅",
  tempatsampah: "🗑️",
  penggaris: "📐",
};
